try:
    print(x)
except:
    print("a error has been occured")   